### ISSUE TITLE
Feature Request: Max GHS purchased per 24hrs.

### ISSUE THREAD

**Issue by RevREB** [Eloque/CexControl#14]
Maybe Ive just over looking a method to accomplish this for myself.
BUT...
Id love to be able to set a max GHS per day to buy. 
What are your thoughts, is it something that is accomplish-able with out a huge rework (which is what I saw)...

Thanks ahead of time.

**Comment by Eloque** [comment]
It would not be that hard I suppose, but I've seen very little call for this.

**Comment by RevREB** [comment]
im closing this cause its hella old :)
