### ISSUE TITLE
Implement limit trading

### ISSUE THREAD

**Issue by ksolomon** [Eloque/CexControl#2]
I would like to be able to specify a minimum and maximum limit for trading , for BTC mainly, but if you have to do both BTC and NMC to make it make sense, that would be fine too.

**Comment by Hector1313** [comment]
This is the only script that was well enough described and set-up for a Noob like me to get working pretty much straight away. Many thanks! Can anyone clarify how to use the 'threshold' values, please? 
It would be cool to be able to specify 'Buy X amount when price falls to A' and 'sell X amount when price rises to B' values. Is it insanely hard to implement an 'instant purchase/sell when price falls/rises to X' adaptation?
Cheers!

**Comment by Eloque** [comment]
Well, Limit trading is not planned yet. If enough people support it, I might build it in.
Thresholds are easy, the script will only trade when a threshold is reached.

**Comment by Eloque** [comment]
I heard no more requests for these functions, as such I am not currently planning to implement them.
