### ISSUE TITLE
LTC Trading

### ISSUE THREAD

**Issue by if12b070** [Eloque/CexControl#3]
Hi,

I just noticed, that CEX.io has implemented LTC now.
Could you implement that too?

**Comment by Eloque** [comment]
Would love to, but what is there to implement?

**Comment by if12b070** [comment]
Well, I thought one could mine LTC on CEX.io. But right now they implemented only trading.

Maybe LTC would be interesting as TargetCoin?

**Comment by Eloque** [comment]
Could be, if LTC/GHS trading is added, i'll include it.

**Comment by HearNoMore** [comment]
They have a LTC/BTC trading... could be cool if the LTC trades into BTC and then buy the GHS then. Whats your thoughts on that?

**Comment by Eloque** [comment]
That's not an issue I suppose. You'd want to auto convert to BTC and then buy GHS? 
Fairly trivial to make. I'll see what I can do.

**Comment by Eloque** [comment]
I've made it so that this happens for IXC/BTC, for LTC it's on the list.

**Comment by Eloque** [comment]
LTC trading has been added.
