### ISSUE TITLE
<type 'exceptions.TypeError'>

### ISSUE THREAD

**Issue by if12b070** [Eloque/CexControl#5]
Hi, 

there was this strange <type 'exceptions.TypeError'>" error.

However, someone solved it. See here:
https://support.cex.io/hc/communities/public/questions/200783667-Official-Eloque-reinvestment-python-script-troubleshooting/answers/201604788

If you change
Ask = ConvertUnicodeFloatToFloat(ticker["ask"])
Bid = ConvertUnicodeFloatToFloat(ticker["bid"])
to
Ask = ticker["ask"]
Bid = ticker["bid"]

in the GetPrice Function everything works fine again.

**Comment by Eloque** [comment]
API had changed, used to receive prices as Unicode strings, now as floats. I implemented the solution as described above. Kudos to however found it.
